functions = {
    'AbortGeneration':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'AdjustSampleClockRelativeDelay':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'adjustmentTime',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'AllocateNamedWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformSize',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'AllocateWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformSize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'waveformHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CalAdjustDirectPathOutputImpedance':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'configuration',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'loadImpedance',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'measuredSourceVoltage',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'measuredVoltageAcrossLoad',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'CalAdjustMainPathOutputImpedance':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'configuration',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'loadImpedance',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'measuredSourceVoltage',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'measuredVoltageAcrossLoad',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'CalAdjustOscillatorFrequency':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'desiredFrequency',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'measuredFrequency',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ChangeExtCalPassword':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'oldPassword',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'newPassword',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'CheckAttributeViBoolean':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'CheckAttributeViInt32':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CheckAttributeViInt64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViInt64'
            }
        ],
        'returns':'ViStatus'
    },
    'CheckAttributeViReal64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'CheckAttributeViSession':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'CheckAttributeViString':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearArbMemory':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearArbSequence':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'sequenceHandle',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearArbWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'waveformHandle',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearError':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearFreqList':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'frequencyListHandle',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearInterchangeWarnings':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ClearUserStandardWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'Close':{
        'cname' : 'niFgen_close',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'CloseExtCal':{
        'custom_close_method': True,
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'action',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'Commit':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureAmplitude':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'amplitude',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureArbSequence':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'sequenceHandle',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'gain',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'offset',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureArbWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformHandle',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'gain',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'offset',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureChannels':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channels',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureClockMode':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'clockMode',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureCustomFirFilterCoefficients':{
        'cname' : 'niFgen_ConfigureCustomFIRFilterCoefficients',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'numberOfCoefficients',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'coefficientsArray',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'numberOfCoefficients'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureDigitalEdgeScriptTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'triggerId',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'source',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'edge',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureDigitalEdgeStartTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'source',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'edge',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureDigitalLevelScriptTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'triggerId',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'source',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'triggerWhen',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureFreqList':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'frequencyListHandle',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'amplitude',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'dcOffset',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'startPhase',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureFrequency':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'frequency',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureGain':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'gain',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureOperationMode':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'operationMode',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureOutputEnabled':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'enabled',
                'direction':'in',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureOutputImpedance':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'impedance',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureOutputMode':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'outputMode',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureP2pEndpointFullnessStartTrigger':{
        'cname' : 'niFgen_ConfigureP2PEndpointFullnessStartTrigger',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'p2pEndpointFullnessLevel',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureRefClockFrequency':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'referenceClockFrequency',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureRefClockSource':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'referenceClockSource',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureReferenceClock':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'referenceClockSource',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'referenceClockFrequency',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureSampleClockSource':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'sampleClockSource',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureSampleRate':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'sampleRate',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureSoftwareEdgeScriptTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'triggerId',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureSoftwareEdgeStartTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureStandardWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveform',
                'direction':'in',
                'type':'ViInt32',
                'enum':'Waveform'
            },
            {
                'name':'amplitude',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'dcOffset',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'frequency',
                'direction':'in',
                'type':'ViReal64'
            },
            {
                'name':'startPhase',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureSynchronization':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'synchronizationSource',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureTriggerMode':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'triggerMode',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureTriggerSource':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'triggerSource',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ConfigureUpdateClockSource':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'updateClockSource',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CreateArbSequence':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'sequenceLength',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'waveformHandlesArray',
                'direction':'in',
                'type':'ViInt32[]',
                'size':{
                    'mechanism':'len',
                    'value':'sequenceLength'
                }
            },
            {
                'name':'loopCountsArray',
                'direction':'in',
                'type':'ViInt32[]',
                'size':{
                    'mechanism':'len',
                    'value':'sequenceLength'
                }
            },
            {
                'name':'sequenceHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CreateFreqList':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'waveform',
                'direction':'in',
                'type':'ViInt32',
                'enum':'Waveform'
            },
            {
                'name':'frequencyListLength',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'frequencyArray',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'frequencyListLength'
                }
            },
            {
                'name':'durationArray',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'frequencyListLength'
                }
            },
            {
                'name':'frequencyListHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CreateWaveformF64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformSize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'waveformDataArray',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'waveformSize'
                }
            },
            {
                'name':'waveformHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CreateWaveformFromFileF64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'fileName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'byteOrder',
                'direction':'in',
                'type':'ViInt32',
                'enum':'ByteOrder'
            },
            {
                'name':'waveformHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CreateWaveformFromFileHws':{
        'cname' : 'niFgen_CreateWaveformFromFileHWS',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'fileName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'useRateFromWaveform',
                'direction':'in',
                'type':'ViBoolean'
            },
            {
                'name':'useGainAndOffsetFromWaveform',
                'direction':'in',
                'type':'ViBoolean'
            },
            {
                'name':'waveformHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'CreateWaveformFromFileI16':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'fileName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'byteOrder',
                'direction':'in',
                'type':'ViInt32',
                'enum':'ByteOrder'
            },
            {
                'name':'waveformHandle',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'DefineUserStandardWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformSize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'waveformDataArray',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'waveformSize'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'DeleteNamedWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'DeleteScript':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'scriptName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'Disable':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'DisableAnalogFilter':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'DisableDigitalFilter':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'DisableDigitalPatterning':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'DisableScriptTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'triggerId',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'DisableStartTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'EnableAnalogFilter':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'filterCorrectionFrequency',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'EnableDigitalFilter':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'EnableDigitalPatterning':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'ErrorMessage':{
        'cname' : 'niFgen_error_message',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'errorCode',
                'direction':'in',
                'type':'ViStatus'
            },
            {
                'name':'errorMessage',
                'direction':'out',
                'type':'ViChar[]',
                'size':{
                    'mechanism':'fixed',
                    'value':256
                }
            }
        ],
        'returns':'ViStatus'
    },
    'ExportAttributeConfigurationBuffer':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'sizeInBytes',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'configuration',
                'direction':'out',
                'type':'ViAddr[]',
                'size':{
                    'mechanism':'ivi-dance',
                    'value':'sizeInBytes'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'ExportAttributeConfigurationFile':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'filePath',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'ExportSignal':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'signal',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'signalIdentifier',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'outputTerminal',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'GetAttributeViBoolean':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'out',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'GetAttributeViInt32':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'GetAttributeViInt64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'out',
                'type':'ViInt64'
            }
        ],
        'returns':'ViStatus'
    },
    'GetAttributeViReal64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'out',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'GetAttributeViSession':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'out',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'GetAttributeViString':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'arraySize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'attributeValue',
                'direction':'out',
                'type':'ViChar[]',
                'size':{
                    'mechanism':'ivi-dance',
                    'value':'arraySize'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'GetCalUserDefinedInfo':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'info',
                'direction':'in',
                'type':'ViChar[]',
                'size':{
                    'mechanism':'fixed',
                    'value':256
                }
            }
        ],
        'returns':'ViStatus'
    },
    'GetCalUserDefinedInfoMaxSize':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'infoSize',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'GetChannelName':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'index',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'bufferSize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'channelString',
                'direction':'out',
                'type':'ViChar[]',
                'size':{
                    'mechanism':'ivi-dance',
                    'value':'bufferSize'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'GetError':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'errorCode',
                'direction':'out',
                'type':'ViStatus'
            },
            {
                'name':'errorDescriptionBufferSize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'errorDescription',
                'direction':'out',
                'type':'ViChar[]',
                'size':{
                    'mechanism':'ivi-dance',
                    'value':'errorDescriptionBufferSize'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'GetExtCalLastDateAndTime':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'year',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'month',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'day',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'hour',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'minute',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'GetExtCalLastTemp':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'temperature',
                'direction':'out',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'GetExtCalRecommendedInterval':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'months',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'GetFirFilterCoefficients':{
        'cname' : 'niFgen_GetFIRFilterCoefficients',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'arraySize',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'coefficientsArray',
                'direction':'out',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'ivi-dance-with-a-twist',
                    'value':'arraySize',
                    'value_twist':'numberOfCoefficientsRead',
                }
            },
            {
                'name':'numberOfCoefficientsRead',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'GetHardwareState':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'state',
                'direction':'out',
                'type':'ViInt32',
                'enum':'HardwareState'
            }
        ],
        'returns':'ViStatus'
    },
    'GetSelfCalLastDateAndTime':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'year',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'month',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'day',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'hour',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'minute',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'GetSelfCalLastTemp':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'temperature',
                'direction':'out',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'GetSelfCalSupported':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'selfCalSupported',
                'direction':'out',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'GetStreamEndpointHandle':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'streamEndpoint',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'readerHandle',
                'direction':'out',
                'type':'ViUInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'ImportAttributeConfigurationBuffer':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'sizeInBytes',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'configuration',
                'direction':'in',
                'type':'ViAddr[]',
                'size':{
                    'mechanism':'len',
                    'value':'sizeInBytes'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'ImportAttributeConfigurationFile':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'filePath',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'InitExtCal':{
        'init_method' : True,
        'custom_close': 'CloseExtCal(id, NIFGEN_VAL_EXT_CAL_ABORT)',
        'parameters':[
            {
                'name':'resourceName',
                'direction':'in',
                'type':'ViRsrc'
            },
            {
                'name':'password',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'vi',
                'direction':'out',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitWithOptions':{
        'init_method' : True,
        'parameters':[
            {
                'name':'resourceName',
                'direction':'in',
                'type':'ViRsrc'
            },
            {
                'name':'idQuery',
                'direction':'in',
                'type':'ViBoolean'
            },
            {
                'name':'resetDevice',
                'direction':'in',
                'type':'ViBoolean'
            },
            {
                'name':'optionString',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'vi',
                'direction':'out',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitializeWithChannels':{
        'init_method' : True,    
        'parameters':[
            {
                'name':'resourceName',
                'direction':'in',
                'type':'ViRsrc'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'resetDevice',
                'direction':'in',
                'type':'ViBoolean'
            },
            {
                'name':'optionString',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'vi',
                'direction':'out',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitializeAnalogOutputCalibration':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitializeCalAdcCalibration':{
        'cname' : 'niFgen_InitializeCalADCCalibration',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitializeFlatnessCalibration':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitializeOscillatorFrequencyCalibration':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InitiateGeneration':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'InvalidateAllAttributes':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'IsDone':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'done',
                'direction':'out',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'LockSession':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'callerHasLock',
                'direction':'out',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'ManualEnableP2pStream':{
        'cname' : 'niFgen_ManualEnableP2PStream',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'endpointName',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'QueryArbSeqCapabilities':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'maximumNumberOfSequences',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'minimumSequenceLength',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'maximumSequenceLength',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'maximumLoopCount',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'QueryArbWfmCapabilities':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'maximumNumberOfWaveforms',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'waveformQuantum',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'minimumWaveformSize',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'maximumWaveformSize',
                'direction':'out',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'QueryFreqListCapabilities':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'maximumNumberOfFreqLists',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'minimumFrequencyListLength',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'maximumFrequencyListLength',
                'direction':'out',
                'type':'ViInt32'
            },
            {
                'name':'minimumFrequencyListDuration',
                'direction':'out',
                'type':'ViReal64'
            },
            {
                'name':'maximumFrequencyListDuration',
                'direction':'out',
                'type':'ViReal64'
            },
            {
                'name':'frequencyListDurationQuantum',
                'direction':'out',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ReadCalAdc':{
        'cname' : 'niFgen_ReadCalADC',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'numberOfReadsToAverage',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'returnCalibratedValue',
                'direction':'in',
                'type':'ViBoolean'
            },
            {
                'name':'calAdcValue',
                'direction':'out',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'ReadCurrentTemperature':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'temperature',
                'direction':'out',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'Reset':{
        'cname' : 'niFgen_reset',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ResetAttribute':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            }
        ],
        'returns':'ViStatus'
    },
    'ResetDevice':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ResetInterchangeCheck':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'ResetWithDefaults':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'RestoreLastExtCalConstants':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'RouteSignalOut':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'routeSignalFrom',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'routeSignalTo',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'SelfCal':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'SelfTest':{
        'cname' : 'niFgen_self_test',
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'selfTestResult',
                'direction':'out',
                'type':'ViInt16'
            },
            {
                'name':'selfTestMessage',
                'direction':'out',
                'type':'ViChar[]',
                'size':{
                    'mechanism':'fixed',
                    'value':256
                }
            }
        ],
        'returns':'ViStatus'
    },
    'SendSoftwareTrigger':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'SetAttributeViBoolean':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'SetAttributeViInt32':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'SetAttributeViInt64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViInt64'
            }
        ],
        'returns':'ViStatus'
    },
    'SetAttributeViReal64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViReal64'
            }
        ],
        'returns':'ViStatus'
    },
    'SetAttributeViSession':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViSession'
            }
        ],
        'returns':'ViStatus'
    },
    'SetAttributeViString':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'attributeId',
                'direction':'in',
                'type':'ViAttr'
            },
            {
                'name':'attributeValue',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'SetCalUserDefinedInfo':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'info',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'SetNamedWaveformNextWritePosition':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'relativeTo',
                'direction':'in',
                'type':'ViInt32',
                'enum':'RelativeTo'
            },
            {
                'name':'offset',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'SetWaveformNextWritePosition':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformHandle',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'relativeTo',
                'direction':'in',
                'type':'ViInt32',
                'enum':'RelativeTo'
            },
            {
                'name':'offset',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'UnlockSession':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'callerHasLock',
                'direction':'out',
                'type':'ViBoolean'
            }
        ],
        'returns':'ViStatus'
    },
    'WaitUntilDone':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'maxTime',
                'direction':'in',
                'type':'ViInt32'
            }
        ],
        'returns':'ViStatus'
    },
    'WriteBinary16AnalogStaticValue':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'value',
                'direction':'in',
                'type':'ViInt16'
            }
        ],
        'returns':'ViStatus'
    },
    'WriteNamedWaveformF64':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'size',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'data',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'size'
                }
            }
        ],
        'returns':'ViStatus'
    },
    'WriteScript':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'script',
                'direction':'in',
                'type':'ViConstString'
            }
        ],
        'returns':'ViStatus'
    },
    'WriteWaveform':{
        'parameters':[
            {
                'name':'vi',
                'direction':'in',
                'type':'ViSession'
            },
            {
                'name':'channelName',
                'direction':'in',
                'type':'ViConstString'
            },
            {
                'name':'waveformHandle',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'size',
                'direction':'in',
                'type':'ViInt32'
            },
            {
                'name':'data',
                'direction':'in',
                'type':'ViReal64[]',
                'size':{
                    'mechanism':'len',
                    'value':'size'
                }
            }
        ],
        'returns':'ViStatus'
    }
}