# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nidmm_pb2 as nidmm__pb2


class NiDMMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Abort = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Abort',
                request_serializer=nidmm__pb2.AbortRequest.SerializeToString,
                response_deserializer=nidmm__pb2.AbortResponse.FromString,
                )
        self.ConfigureMeasurementAbsolute = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureMeasurementAbsolute',
                request_serializer=nidmm__pb2.ConfigureMeasurementAbsoluteRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureMeasurementAbsoluteResponse.FromString,
                )
        self.ConfigureMeasurementDigits = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureMeasurementDigits',
                request_serializer=nidmm__pb2.ConfigureMeasurementDigitsRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureMeasurementDigitsResponse.FromString,
                )
        self.ConfigureMultiPoint = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureMultiPoint',
                request_serializer=nidmm__pb2.ConfigureMultiPointRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureMultiPointResponse.FromString,
                )
        self.ConfigureRTDCustom = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureRTDCustom',
                request_serializer=nidmm__pb2.ConfigureRTDCustomRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureRTDCustomResponse.FromString,
                )
        self.ConfigureRTDType = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureRTDType',
                request_serializer=nidmm__pb2.ConfigureRTDTypeRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureRTDTypeResponse.FromString,
                )
        self.ConfigureThermistorCustom = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureThermistorCustom',
                request_serializer=nidmm__pb2.ConfigureThermistorCustomRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureThermistorCustomResponse.FromString,
                )
        self.ConfigureThermocouple = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureThermocouple',
                request_serializer=nidmm__pb2.ConfigureThermocoupleRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureThermocoupleResponse.FromString,
                )
        self.ConfigureTrigger = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureTrigger',
                request_serializer=nidmm__pb2.ConfigureTriggerRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureTriggerResponse.FromString,
                )
        self.ConfigureWaveformAcquisition = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ConfigureWaveformAcquisition',
                request_serializer=nidmm__pb2.ConfigureWaveformAcquisitionRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ConfigureWaveformAcquisitionResponse.FromString,
                )
        self.Disable = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Disable',
                request_serializer=nidmm__pb2.DisableRequest.SerializeToString,
                response_deserializer=nidmm__pb2.DisableResponse.FromString,
                )
        self.ExportAttributeConfigurationBuffer = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ExportAttributeConfigurationBuffer',
                request_serializer=nidmm__pb2.ExportAttributeConfigurationBufferRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ExportAttributeConfigurationBufferResponse.FromString,
                )
        self.ExportAttributeConfigurationFile = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ExportAttributeConfigurationFile',
                request_serializer=nidmm__pb2.ExportAttributeConfigurationFileRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ExportAttributeConfigurationFileResponse.FromString,
                )
        self.Fetch = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Fetch',
                request_serializer=nidmm__pb2.FetchRequest.SerializeToString,
                response_deserializer=nidmm__pb2.FetchResponse.FromString,
                )
        self.FetchMultiPoint = channel.unary_unary(
                '/nidmm_grpc.NiDMM/FetchMultiPoint',
                request_serializer=nidmm__pb2.FetchMultiPointRequest.SerializeToString,
                response_deserializer=nidmm__pb2.FetchMultiPointResponse.FromString,
                )
        self.FetchWaveform = channel.unary_unary(
                '/nidmm_grpc.NiDMM/FetchWaveform',
                request_serializer=nidmm__pb2.FetchWaveformRequest.SerializeToString,
                response_deserializer=nidmm__pb2.FetchWaveformResponse.FromString,
                )
        self.GetAttributeViBoolean = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetAttributeViBoolean',
                request_serializer=nidmm__pb2.GetAttributeViBooleanRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetAttributeViBooleanResponse.FromString,
                )
        self.GetAttributeViInt32 = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetAttributeViInt32',
                request_serializer=nidmm__pb2.GetAttributeViInt32Request.SerializeToString,
                response_deserializer=nidmm__pb2.GetAttributeViInt32Response.FromString,
                )
        self.GetAttributeViReal64 = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetAttributeViReal64',
                request_serializer=nidmm__pb2.GetAttributeViReal64Request.SerializeToString,
                response_deserializer=nidmm__pb2.GetAttributeViReal64Response.FromString,
                )
        self.GetAttributeViString = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetAttributeViString',
                request_serializer=nidmm__pb2.GetAttributeViStringRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetAttributeViStringResponse.FromString,
                )
        self.GetCalDateAndTime = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetCalDateAndTime',
                request_serializer=nidmm__pb2.GetCalDateAndTimeRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetCalDateAndTimeResponse.FromString,
                )
        self.GetDevTemp = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetDevTemp',
                request_serializer=nidmm__pb2.GetDevTempRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetDevTempResponse.FromString,
                )
        self.GetError = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetError',
                request_serializer=nidmm__pb2.GetErrorRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetErrorResponse.FromString,
                )
        self.GetExtCalRecommendedInterval = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetExtCalRecommendedInterval',
                request_serializer=nidmm__pb2.GetExtCalRecommendedIntervalRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetExtCalRecommendedIntervalResponse.FromString,
                )
        self.GetLastCalTemp = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetLastCalTemp',
                request_serializer=nidmm__pb2.GetLastCalTempRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetLastCalTempResponse.FromString,
                )
        self.GetSelfCalSupported = channel.unary_unary(
                '/nidmm_grpc.NiDMM/GetSelfCalSupported',
                request_serializer=nidmm__pb2.GetSelfCalSupportedRequest.SerializeToString,
                response_deserializer=nidmm__pb2.GetSelfCalSupportedResponse.FromString,
                )
        self.ImportAttributeConfigurationBuffer = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ImportAttributeConfigurationBuffer',
                request_serializer=nidmm__pb2.ImportAttributeConfigurationBufferRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ImportAttributeConfigurationBufferResponse.FromString,
                )
        self.ImportAttributeConfigurationFile = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ImportAttributeConfigurationFile',
                request_serializer=nidmm__pb2.ImportAttributeConfigurationFileRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ImportAttributeConfigurationFileResponse.FromString,
                )
        self.Init = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Init',
                request_serializer=nidmm__pb2.InitRequest.SerializeToString,
                response_deserializer=nidmm__pb2.InitResponse.FromString,
                )
        self.InitWithOptions = channel.unary_unary(
                '/nidmm_grpc.NiDMM/InitWithOptions',
                request_serializer=nidmm__pb2.InitWithOptionsRequest.SerializeToString,
                response_deserializer=nidmm__pb2.InitWithOptionsResponse.FromString,
                )
        self.Initiate = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Initiate',
                request_serializer=nidmm__pb2.InitiateRequest.SerializeToString,
                response_deserializer=nidmm__pb2.InitiateResponse.FromString,
                )
        self.LockSession = channel.unary_unary(
                '/nidmm_grpc.NiDMM/LockSession',
                request_serializer=nidmm__pb2.LockSessionRequest.SerializeToString,
                response_deserializer=nidmm__pb2.LockSessionResponse.FromString,
                )
        self.PerformOpenCableComp = channel.unary_unary(
                '/nidmm_grpc.NiDMM/PerformOpenCableComp',
                request_serializer=nidmm__pb2.PerformOpenCableCompRequest.SerializeToString,
                response_deserializer=nidmm__pb2.PerformOpenCableCompResponse.FromString,
                )
        self.PerformShortCableComp = channel.unary_unary(
                '/nidmm_grpc.NiDMM/PerformShortCableComp',
                request_serializer=nidmm__pb2.PerformShortCableCompRequest.SerializeToString,
                response_deserializer=nidmm__pb2.PerformShortCableCompResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Read',
                request_serializer=nidmm__pb2.ReadRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ReadResponse.FromString,
                )
        self.ReadMultiPoint = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ReadMultiPoint',
                request_serializer=nidmm__pb2.ReadMultiPointRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ReadMultiPointResponse.FromString,
                )
        self.ReadStatus = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ReadStatus',
                request_serializer=nidmm__pb2.ReadStatusRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ReadStatusResponse.FromString,
                )
        self.ReadWaveform = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ReadWaveform',
                request_serializer=nidmm__pb2.ReadWaveformRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ReadWaveformResponse.FromString,
                )
        self.ResetWithDefaults = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ResetWithDefaults',
                request_serializer=nidmm__pb2.ResetWithDefaultsRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ResetWithDefaultsResponse.FromString,
                )
        self.SelfCal = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SelfCal',
                request_serializer=nidmm__pb2.SelfCalRequest.SerializeToString,
                response_deserializer=nidmm__pb2.SelfCalResponse.FromString,
                )
        self.SendSoftwareTrigger = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SendSoftwareTrigger',
                request_serializer=nidmm__pb2.SendSoftwareTriggerRequest.SerializeToString,
                response_deserializer=nidmm__pb2.SendSoftwareTriggerResponse.FromString,
                )
        self.SetAttributeViBoolean = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SetAttributeViBoolean',
                request_serializer=nidmm__pb2.SetAttributeViBooleanRequest.SerializeToString,
                response_deserializer=nidmm__pb2.SetAttributeViBooleanResponse.FromString,
                )
        self.SetAttributeViInt32 = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SetAttributeViInt32',
                request_serializer=nidmm__pb2.SetAttributeViInt32Request.SerializeToString,
                response_deserializer=nidmm__pb2.SetAttributeViInt32Response.FromString,
                )
        self.SetAttributeViReal64 = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SetAttributeViReal64',
                request_serializer=nidmm__pb2.SetAttributeViReal64Request.SerializeToString,
                response_deserializer=nidmm__pb2.SetAttributeViReal64Response.FromString,
                )
        self.SetAttributeViString = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SetAttributeViString',
                request_serializer=nidmm__pb2.SetAttributeViStringRequest.SerializeToString,
                response_deserializer=nidmm__pb2.SetAttributeViStringResponse.FromString,
                )
        self.UnlockSession = channel.unary_unary(
                '/nidmm_grpc.NiDMM/UnlockSession',
                request_serializer=nidmm__pb2.UnlockSessionRequest.SerializeToString,
                response_deserializer=nidmm__pb2.UnlockSessionResponse.FromString,
                )
        self.Close = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Close',
                request_serializer=nidmm__pb2.CloseRequest.SerializeToString,
                response_deserializer=nidmm__pb2.CloseResponse.FromString,
                )
        self.ErrorMessage = channel.unary_unary(
                '/nidmm_grpc.NiDMM/ErrorMessage',
                request_serializer=nidmm__pb2.ErrorMessageRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ErrorMessageResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/nidmm_grpc.NiDMM/Reset',
                request_serializer=nidmm__pb2.ResetRequest.SerializeToString,
                response_deserializer=nidmm__pb2.ResetResponse.FromString,
                )
        self.SelfTest = channel.unary_unary(
                '/nidmm_grpc.NiDMM/SelfTest',
                request_serializer=nidmm__pb2.SelfTestRequest.SerializeToString,
                response_deserializer=nidmm__pb2.SelfTestResponse.FromString,
                )


class NiDMMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureMeasurementAbsolute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureMeasurementDigits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureMultiPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureRTDCustom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureRTDType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureThermistorCustom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureThermocouple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureWaveformAcquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportAttributeConfigurationBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportAttributeConfigurationFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchMultiPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchWaveform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeViBoolean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeViInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeViReal64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeViString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalDateAndTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtCalRecommendedInterval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastCalTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSelfCalSupported(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportAttributeConfigurationBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportAttributeConfigurationFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitWithOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initiate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformOpenCableComp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformShortCableComp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMultiPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadWaveform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetWithDefaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelfCal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSoftwareTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttributeViBoolean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttributeViInt32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttributeViReal64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttributeViString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ErrorMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelfTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NiDMMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=nidmm__pb2.AbortRequest.FromString,
                    response_serializer=nidmm__pb2.AbortResponse.SerializeToString,
            ),
            'ConfigureMeasurementAbsolute': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureMeasurementAbsolute,
                    request_deserializer=nidmm__pb2.ConfigureMeasurementAbsoluteRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureMeasurementAbsoluteResponse.SerializeToString,
            ),
            'ConfigureMeasurementDigits': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureMeasurementDigits,
                    request_deserializer=nidmm__pb2.ConfigureMeasurementDigitsRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureMeasurementDigitsResponse.SerializeToString,
            ),
            'ConfigureMultiPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureMultiPoint,
                    request_deserializer=nidmm__pb2.ConfigureMultiPointRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureMultiPointResponse.SerializeToString,
            ),
            'ConfigureRTDCustom': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureRTDCustom,
                    request_deserializer=nidmm__pb2.ConfigureRTDCustomRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureRTDCustomResponse.SerializeToString,
            ),
            'ConfigureRTDType': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureRTDType,
                    request_deserializer=nidmm__pb2.ConfigureRTDTypeRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureRTDTypeResponse.SerializeToString,
            ),
            'ConfigureThermistorCustom': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureThermistorCustom,
                    request_deserializer=nidmm__pb2.ConfigureThermistorCustomRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureThermistorCustomResponse.SerializeToString,
            ),
            'ConfigureThermocouple': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureThermocouple,
                    request_deserializer=nidmm__pb2.ConfigureThermocoupleRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureThermocoupleResponse.SerializeToString,
            ),
            'ConfigureTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureTrigger,
                    request_deserializer=nidmm__pb2.ConfigureTriggerRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureTriggerResponse.SerializeToString,
            ),
            'ConfigureWaveformAcquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureWaveformAcquisition,
                    request_deserializer=nidmm__pb2.ConfigureWaveformAcquisitionRequest.FromString,
                    response_serializer=nidmm__pb2.ConfigureWaveformAcquisitionResponse.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=nidmm__pb2.DisableRequest.FromString,
                    response_serializer=nidmm__pb2.DisableResponse.SerializeToString,
            ),
            'ExportAttributeConfigurationBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportAttributeConfigurationBuffer,
                    request_deserializer=nidmm__pb2.ExportAttributeConfigurationBufferRequest.FromString,
                    response_serializer=nidmm__pb2.ExportAttributeConfigurationBufferResponse.SerializeToString,
            ),
            'ExportAttributeConfigurationFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportAttributeConfigurationFile,
                    request_deserializer=nidmm__pb2.ExportAttributeConfigurationFileRequest.FromString,
                    response_serializer=nidmm__pb2.ExportAttributeConfigurationFileResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=nidmm__pb2.FetchRequest.FromString,
                    response_serializer=nidmm__pb2.FetchResponse.SerializeToString,
            ),
            'FetchMultiPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMultiPoint,
                    request_deserializer=nidmm__pb2.FetchMultiPointRequest.FromString,
                    response_serializer=nidmm__pb2.FetchMultiPointResponse.SerializeToString,
            ),
            'FetchWaveform': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchWaveform,
                    request_deserializer=nidmm__pb2.FetchWaveformRequest.FromString,
                    response_serializer=nidmm__pb2.FetchWaveformResponse.SerializeToString,
            ),
            'GetAttributeViBoolean': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeViBoolean,
                    request_deserializer=nidmm__pb2.GetAttributeViBooleanRequest.FromString,
                    response_serializer=nidmm__pb2.GetAttributeViBooleanResponse.SerializeToString,
            ),
            'GetAttributeViInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeViInt32,
                    request_deserializer=nidmm__pb2.GetAttributeViInt32Request.FromString,
                    response_serializer=nidmm__pb2.GetAttributeViInt32Response.SerializeToString,
            ),
            'GetAttributeViReal64': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeViReal64,
                    request_deserializer=nidmm__pb2.GetAttributeViReal64Request.FromString,
                    response_serializer=nidmm__pb2.GetAttributeViReal64Response.SerializeToString,
            ),
            'GetAttributeViString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeViString,
                    request_deserializer=nidmm__pb2.GetAttributeViStringRequest.FromString,
                    response_serializer=nidmm__pb2.GetAttributeViStringResponse.SerializeToString,
            ),
            'GetCalDateAndTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalDateAndTime,
                    request_deserializer=nidmm__pb2.GetCalDateAndTimeRequest.FromString,
                    response_serializer=nidmm__pb2.GetCalDateAndTimeResponse.SerializeToString,
            ),
            'GetDevTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevTemp,
                    request_deserializer=nidmm__pb2.GetDevTempRequest.FromString,
                    response_serializer=nidmm__pb2.GetDevTempResponse.SerializeToString,
            ),
            'GetError': grpc.unary_unary_rpc_method_handler(
                    servicer.GetError,
                    request_deserializer=nidmm__pb2.GetErrorRequest.FromString,
                    response_serializer=nidmm__pb2.GetErrorResponse.SerializeToString,
            ),
            'GetExtCalRecommendedInterval': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtCalRecommendedInterval,
                    request_deserializer=nidmm__pb2.GetExtCalRecommendedIntervalRequest.FromString,
                    response_serializer=nidmm__pb2.GetExtCalRecommendedIntervalResponse.SerializeToString,
            ),
            'GetLastCalTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastCalTemp,
                    request_deserializer=nidmm__pb2.GetLastCalTempRequest.FromString,
                    response_serializer=nidmm__pb2.GetLastCalTempResponse.SerializeToString,
            ),
            'GetSelfCalSupported': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSelfCalSupported,
                    request_deserializer=nidmm__pb2.GetSelfCalSupportedRequest.FromString,
                    response_serializer=nidmm__pb2.GetSelfCalSupportedResponse.SerializeToString,
            ),
            'ImportAttributeConfigurationBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportAttributeConfigurationBuffer,
                    request_deserializer=nidmm__pb2.ImportAttributeConfigurationBufferRequest.FromString,
                    response_serializer=nidmm__pb2.ImportAttributeConfigurationBufferResponse.SerializeToString,
            ),
            'ImportAttributeConfigurationFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportAttributeConfigurationFile,
                    request_deserializer=nidmm__pb2.ImportAttributeConfigurationFileRequest.FromString,
                    response_serializer=nidmm__pb2.ImportAttributeConfigurationFileResponse.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=nidmm__pb2.InitRequest.FromString,
                    response_serializer=nidmm__pb2.InitResponse.SerializeToString,
            ),
            'InitWithOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.InitWithOptions,
                    request_deserializer=nidmm__pb2.InitWithOptionsRequest.FromString,
                    response_serializer=nidmm__pb2.InitWithOptionsResponse.SerializeToString,
            ),
            'Initiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Initiate,
                    request_deserializer=nidmm__pb2.InitiateRequest.FromString,
                    response_serializer=nidmm__pb2.InitiateResponse.SerializeToString,
            ),
            'LockSession': grpc.unary_unary_rpc_method_handler(
                    servicer.LockSession,
                    request_deserializer=nidmm__pb2.LockSessionRequest.FromString,
                    response_serializer=nidmm__pb2.LockSessionResponse.SerializeToString,
            ),
            'PerformOpenCableComp': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformOpenCableComp,
                    request_deserializer=nidmm__pb2.PerformOpenCableCompRequest.FromString,
                    response_serializer=nidmm__pb2.PerformOpenCableCompResponse.SerializeToString,
            ),
            'PerformShortCableComp': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformShortCableComp,
                    request_deserializer=nidmm__pb2.PerformShortCableCompRequest.FromString,
                    response_serializer=nidmm__pb2.PerformShortCableCompResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=nidmm__pb2.ReadRequest.FromString,
                    response_serializer=nidmm__pb2.ReadResponse.SerializeToString,
            ),
            'ReadMultiPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMultiPoint,
                    request_deserializer=nidmm__pb2.ReadMultiPointRequest.FromString,
                    response_serializer=nidmm__pb2.ReadMultiPointResponse.SerializeToString,
            ),
            'ReadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadStatus,
                    request_deserializer=nidmm__pb2.ReadStatusRequest.FromString,
                    response_serializer=nidmm__pb2.ReadStatusResponse.SerializeToString,
            ),
            'ReadWaveform': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadWaveform,
                    request_deserializer=nidmm__pb2.ReadWaveformRequest.FromString,
                    response_serializer=nidmm__pb2.ReadWaveformResponse.SerializeToString,
            ),
            'ResetWithDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetWithDefaults,
                    request_deserializer=nidmm__pb2.ResetWithDefaultsRequest.FromString,
                    response_serializer=nidmm__pb2.ResetWithDefaultsResponse.SerializeToString,
            ),
            'SelfCal': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfCal,
                    request_deserializer=nidmm__pb2.SelfCalRequest.FromString,
                    response_serializer=nidmm__pb2.SelfCalResponse.SerializeToString,
            ),
            'SendSoftwareTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSoftwareTrigger,
                    request_deserializer=nidmm__pb2.SendSoftwareTriggerRequest.FromString,
                    response_serializer=nidmm__pb2.SendSoftwareTriggerResponse.SerializeToString,
            ),
            'SetAttributeViBoolean': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttributeViBoolean,
                    request_deserializer=nidmm__pb2.SetAttributeViBooleanRequest.FromString,
                    response_serializer=nidmm__pb2.SetAttributeViBooleanResponse.SerializeToString,
            ),
            'SetAttributeViInt32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttributeViInt32,
                    request_deserializer=nidmm__pb2.SetAttributeViInt32Request.FromString,
                    response_serializer=nidmm__pb2.SetAttributeViInt32Response.SerializeToString,
            ),
            'SetAttributeViReal64': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttributeViReal64,
                    request_deserializer=nidmm__pb2.SetAttributeViReal64Request.FromString,
                    response_serializer=nidmm__pb2.SetAttributeViReal64Response.SerializeToString,
            ),
            'SetAttributeViString': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttributeViString,
                    request_deserializer=nidmm__pb2.SetAttributeViStringRequest.FromString,
                    response_serializer=nidmm__pb2.SetAttributeViStringResponse.SerializeToString,
            ),
            'UnlockSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockSession,
                    request_deserializer=nidmm__pb2.UnlockSessionRequest.FromString,
                    response_serializer=nidmm__pb2.UnlockSessionResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=nidmm__pb2.CloseRequest.FromString,
                    response_serializer=nidmm__pb2.CloseResponse.SerializeToString,
            ),
            'ErrorMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ErrorMessage,
                    request_deserializer=nidmm__pb2.ErrorMessageRequest.FromString,
                    response_serializer=nidmm__pb2.ErrorMessageResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=nidmm__pb2.ResetRequest.FromString,
                    response_serializer=nidmm__pb2.ResetResponse.SerializeToString,
            ),
            'SelfTest': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfTest,
                    request_deserializer=nidmm__pb2.SelfTestRequest.FromString,
                    response_serializer=nidmm__pb2.SelfTestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nidmm_grpc.NiDMM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NiDMM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Abort',
            nidmm__pb2.AbortRequest.SerializeToString,
            nidmm__pb2.AbortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureMeasurementAbsolute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureMeasurementAbsolute',
            nidmm__pb2.ConfigureMeasurementAbsoluteRequest.SerializeToString,
            nidmm__pb2.ConfigureMeasurementAbsoluteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureMeasurementDigits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureMeasurementDigits',
            nidmm__pb2.ConfigureMeasurementDigitsRequest.SerializeToString,
            nidmm__pb2.ConfigureMeasurementDigitsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureMultiPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureMultiPoint',
            nidmm__pb2.ConfigureMultiPointRequest.SerializeToString,
            nidmm__pb2.ConfigureMultiPointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureRTDCustom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureRTDCustom',
            nidmm__pb2.ConfigureRTDCustomRequest.SerializeToString,
            nidmm__pb2.ConfigureRTDCustomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureRTDType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureRTDType',
            nidmm__pb2.ConfigureRTDTypeRequest.SerializeToString,
            nidmm__pb2.ConfigureRTDTypeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureThermistorCustom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureThermistorCustom',
            nidmm__pb2.ConfigureThermistorCustomRequest.SerializeToString,
            nidmm__pb2.ConfigureThermistorCustomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureThermocouple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureThermocouple',
            nidmm__pb2.ConfigureThermocoupleRequest.SerializeToString,
            nidmm__pb2.ConfigureThermocoupleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureTrigger',
            nidmm__pb2.ConfigureTriggerRequest.SerializeToString,
            nidmm__pb2.ConfigureTriggerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigureWaveformAcquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ConfigureWaveformAcquisition',
            nidmm__pb2.ConfigureWaveformAcquisitionRequest.SerializeToString,
            nidmm__pb2.ConfigureWaveformAcquisitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Disable',
            nidmm__pb2.DisableRequest.SerializeToString,
            nidmm__pb2.DisableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportAttributeConfigurationBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ExportAttributeConfigurationBuffer',
            nidmm__pb2.ExportAttributeConfigurationBufferRequest.SerializeToString,
            nidmm__pb2.ExportAttributeConfigurationBufferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportAttributeConfigurationFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ExportAttributeConfigurationFile',
            nidmm__pb2.ExportAttributeConfigurationFileRequest.SerializeToString,
            nidmm__pb2.ExportAttributeConfigurationFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Fetch',
            nidmm__pb2.FetchRequest.SerializeToString,
            nidmm__pb2.FetchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchMultiPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/FetchMultiPoint',
            nidmm__pb2.FetchMultiPointRequest.SerializeToString,
            nidmm__pb2.FetchMultiPointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchWaveform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/FetchWaveform',
            nidmm__pb2.FetchWaveformRequest.SerializeToString,
            nidmm__pb2.FetchWaveformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttributeViBoolean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetAttributeViBoolean',
            nidmm__pb2.GetAttributeViBooleanRequest.SerializeToString,
            nidmm__pb2.GetAttributeViBooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttributeViInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetAttributeViInt32',
            nidmm__pb2.GetAttributeViInt32Request.SerializeToString,
            nidmm__pb2.GetAttributeViInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttributeViReal64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetAttributeViReal64',
            nidmm__pb2.GetAttributeViReal64Request.SerializeToString,
            nidmm__pb2.GetAttributeViReal64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttributeViString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetAttributeViString',
            nidmm__pb2.GetAttributeViStringRequest.SerializeToString,
            nidmm__pb2.GetAttributeViStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCalDateAndTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetCalDateAndTime',
            nidmm__pb2.GetCalDateAndTimeRequest.SerializeToString,
            nidmm__pb2.GetCalDateAndTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetDevTemp',
            nidmm__pb2.GetDevTempRequest.SerializeToString,
            nidmm__pb2.GetDevTempResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetError',
            nidmm__pb2.GetErrorRequest.SerializeToString,
            nidmm__pb2.GetErrorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExtCalRecommendedInterval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetExtCalRecommendedInterval',
            nidmm__pb2.GetExtCalRecommendedIntervalRequest.SerializeToString,
            nidmm__pb2.GetExtCalRecommendedIntervalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLastCalTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetLastCalTemp',
            nidmm__pb2.GetLastCalTempRequest.SerializeToString,
            nidmm__pb2.GetLastCalTempResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSelfCalSupported(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/GetSelfCalSupported',
            nidmm__pb2.GetSelfCalSupportedRequest.SerializeToString,
            nidmm__pb2.GetSelfCalSupportedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportAttributeConfigurationBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ImportAttributeConfigurationBuffer',
            nidmm__pb2.ImportAttributeConfigurationBufferRequest.SerializeToString,
            nidmm__pb2.ImportAttributeConfigurationBufferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportAttributeConfigurationFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ImportAttributeConfigurationFile',
            nidmm__pb2.ImportAttributeConfigurationFileRequest.SerializeToString,
            nidmm__pb2.ImportAttributeConfigurationFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Init',
            nidmm__pb2.InitRequest.SerializeToString,
            nidmm__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitWithOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/InitWithOptions',
            nidmm__pb2.InitWithOptionsRequest.SerializeToString,
            nidmm__pb2.InitWithOptionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Initiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Initiate',
            nidmm__pb2.InitiateRequest.SerializeToString,
            nidmm__pb2.InitiateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LockSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/LockSession',
            nidmm__pb2.LockSessionRequest.SerializeToString,
            nidmm__pb2.LockSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformOpenCableComp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/PerformOpenCableComp',
            nidmm__pb2.PerformOpenCableCompRequest.SerializeToString,
            nidmm__pb2.PerformOpenCableCompResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformShortCableComp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/PerformShortCableComp',
            nidmm__pb2.PerformShortCableCompRequest.SerializeToString,
            nidmm__pb2.PerformShortCableCompResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Read',
            nidmm__pb2.ReadRequest.SerializeToString,
            nidmm__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadMultiPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ReadMultiPoint',
            nidmm__pb2.ReadMultiPointRequest.SerializeToString,
            nidmm__pb2.ReadMultiPointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ReadStatus',
            nidmm__pb2.ReadStatusRequest.SerializeToString,
            nidmm__pb2.ReadStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadWaveform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ReadWaveform',
            nidmm__pb2.ReadWaveformRequest.SerializeToString,
            nidmm__pb2.ReadWaveformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetWithDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ResetWithDefaults',
            nidmm__pb2.ResetWithDefaultsRequest.SerializeToString,
            nidmm__pb2.ResetWithDefaultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SelfCal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SelfCal',
            nidmm__pb2.SelfCalRequest.SerializeToString,
            nidmm__pb2.SelfCalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendSoftwareTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SendSoftwareTrigger',
            nidmm__pb2.SendSoftwareTriggerRequest.SerializeToString,
            nidmm__pb2.SendSoftwareTriggerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAttributeViBoolean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SetAttributeViBoolean',
            nidmm__pb2.SetAttributeViBooleanRequest.SerializeToString,
            nidmm__pb2.SetAttributeViBooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAttributeViInt32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SetAttributeViInt32',
            nidmm__pb2.SetAttributeViInt32Request.SerializeToString,
            nidmm__pb2.SetAttributeViInt32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAttributeViReal64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SetAttributeViReal64',
            nidmm__pb2.SetAttributeViReal64Request.SerializeToString,
            nidmm__pb2.SetAttributeViReal64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAttributeViString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SetAttributeViString',
            nidmm__pb2.SetAttributeViStringRequest.SerializeToString,
            nidmm__pb2.SetAttributeViStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnlockSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/UnlockSession',
            nidmm__pb2.UnlockSessionRequest.SerializeToString,
            nidmm__pb2.UnlockSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Close',
            nidmm__pb2.CloseRequest.SerializeToString,
            nidmm__pb2.CloseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ErrorMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/ErrorMessage',
            nidmm__pb2.ErrorMessageRequest.SerializeToString,
            nidmm__pb2.ErrorMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/Reset',
            nidmm__pb2.ResetRequest.SerializeToString,
            nidmm__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SelfTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nidmm_grpc.NiDMM/SelfTest',
            nidmm__pb2.SelfTestRequest.SerializeToString,
            nidmm__pb2.SelfTestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
