name: Create Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: ni-grpc-device-client-Linux
        path: downloads/artifacts

    - name: "Create Release"
      uses: ncipollo/release-action@v1
      with:
        artifacts: "downloads/artifacts/*"
        commit: ${{ github.sha }}
        draft: true
        bodyFile: ".github/release_template.md"
        name: "NI gRPC Device Server #.#.#"
        tag: "vx.x.x"
        token: ${{ secrets.GITHUB_TOKEN }}
