name: Create Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@v3
      with:
        name: ni-grpc-device-client
        path: downloads/artifacts

    - uses: actions/download-artifact@v3
      with:
        name: ni-grpc-device-client-Linux
        path: downloads/artifacts

    - uses: actions/download-artifact@v3
      with:
        name: ni-grpc-device-server-linux-glibc2_27-x64
        path: downloads/artifacts

    - uses: actions/download-artifact@v3
      with:
        name: ni-grpc-device-server-ni-linux-rt-x64
        path: downloads/artifacts

    - uses: actions/download-artifact@v3
      with:
        name: ni-grpc-device-server-windows-x64
        path: downloads/artifacts

    - name: "Get previous tag"
      id: previoustag
      run: >-
        echo "::set-output name=tag::$(
          git describe --abbrev=0 --tags ${{github.ref_name}}^
        )"

    - name: "Get next minor version"
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag}}

    - name: "Create Release"
      uses: ncipollo/release-action@v1
      with:
        artifacts: "downloads/artifacts/*"
        commit: ${{ github.sha }}
        draft: true
        generateReleaseNotes: true
        bodyFile: ".github/release_template.md"
        name: "NI gRPC Device Server ${{ steps.semvers.outputs.v_patch }}"
        tag: ${{ steps.semvers.outputs.v_patch }}
        token: ${{ secrets.GITHUB_TOKEN }}
