name: PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
