name: Trigger AzDO CIs

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
      - 'releases/**'
  workflow_dispatch:

jobs:
  trigger_azdo_ci:
    name: Trigger Main CI
    runs-on: windows-latest
    steps:
    - name: Trigger Main CI
      uses: Azure/pipelines@v1
      if: ${{ github.repository == 'ni/grpc-device' && github.event.workflow_run.head_branch == 'main' }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ni-central-grpc_device-main-desktop'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}

    - name: Trigger Release CI
      uses: Azure/pipelines@v1
      if: ${{ github.repository == 'ni/grpc-device' && startsWith(github.event.workflow_run.head_branch, 'releases') }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ni-central-grpc_device-release-desktop'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}

    - name: Trigger Main CI
      uses: Azure/pipelines@v1
      if: ${{ github.repository == 'ni/grpc-device' && github.event.workflow_run.head_branch == 'main' }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ni-central-grpc_device-main-linux-rt'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}

    - name: Trigger Release CI
      uses: Azure/pipelines@v1
      if: ${{ github.repository == 'ni/grpc-device' && startsWith(github.event.workflow_run.head_branch, 'releases') }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ni-central-grpc_device-release-linux-rt'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}
