name: Trigger AzDO CIs

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
      - 'releases/**'
  workflow_dispatch:

jobs:
  trigger_azdo_ci:
    name: Trigger Main CI
    runs-on: windows-latest
    steps:
    - name: Trigger Main CI 
      uses: Azure/pipelines@v1.2
      if: ${{ github.repository == 'ni/grpc-device' && github.event.workflow_run.head_branch == 'main' }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ni-central-grpc_device'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}
        azure-pipeline-variables: '{"BRANCH": "main", "EXPORT_NAME": "ni-grpc-device", "PHASE": "d"}'
                                  
    - name: Trigger Release CI 
      uses: Azure/pipelines@v1.2
      if: ${{ github.repository == 'ni/grpc-device' && startsWith(github.event.workflow_run.head_branch, 'releases') }}
      with:
        azure-devops-project-url: 'https://dev.azure.com/ni/DevCentral'
        azure-pipeline-name: 'ni-central-grpc_device'
        azure-devops-token: ${{ secrets.AZDO_PIPELINE_TRIGGERS }}
        azure-pipeline-variables: '{"BRANCH": "releases", "EXPORT_NAME": "ni-grpc-device", "PHASE": "f", "RELEASE_BRANCH_OPTION": "--release-branch"}'